/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.infinitservices.serviceplatform.bulkuploader;

import static org.assertj.core.api.Assertions.*;

import java.io.IOException;

import org.junit.Before;
import org.junit.Test;

public class ElasticsearchBulkUploaderAppTest {

    private ElasticsearchBulkUploaderApp app;

    @Before
    public void setUp() {
        app = new ElasticsearchBulkUploaderApp();
    }

    @Test
    public void knownIndexShoudReturnOk() throws IOException {
        assertThat(app.lowLevelApi("accounts")).isEqualTo(200);
    }

    @Test
    public void unknownIndexShoudReturnOk() throws IOException {
        assertThat(app.lowLevelApi("enron")).isEqualTo(404);
    }
}
